# Dependencies
markdown:            kramdown
highlighter:         rouge

# Gems (for Jekyll 3.0)
gems: [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               POLPOC CYBERSECURITY
tagline:             'Pentesting Blog'
description:         'Pwning Labs'
url:                 https://polpoc.github.io
baseurl:             /
paginate:            7

# About/contact
author:
  name:              Polpoc
  url:               https://polpoc.github.io
  email:             someone@proton.me

# Custom vars
version:             2.0

# Social Media
github:				https://github.com/PolPoc


